services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017/todo-list
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: